### PR TITLE
Drop polyfills and ship modern code

### PR DESCRIPTION
**Pull request by fregante**
Most browsers don't need most of the transforms that babel-env applies due to its native support for IE11. I highly suggest dropping babel entirely and just ship modern code.

Alternatively `browserslist` can be reduced to only include evergreen browsers.

This PR is incomplete (I also need to drop the dependency altogether), let me know how/if you'd like to proceed.

### CODE REVIEW

**Comment by fregante** [comment]
By the way TypeScript already transpiles code to more compatible versions, babel is just duplicate

https://github.com/fczbkk/css-selector-generator/blob/81f96a7a830006c7098ad076b5880d49ee6e4736/tsconfig.json#L6

**Comment by fczbkk** [comment]
I think Babel is there because of tests, which I did not convert to Typescript. Not sure, I'll have to check.

**Comment by fregante** [comment]
It they do, they don’t seem to go through webpack so this change would not affect the tests, just the users of the library. If you “Approve and run” the CI you can probably immediately prove this. 

If you want I can continue the PR and drop it wherever possible as long as the tests keep working.

**Comment by fczbkk** [comment]
@fregante Closing this pull request. I have removed the Babel dependency in this commit:
https://github.com/fczbkk/css-selector-generator/commit/17e1e2bc1c376c915a1e82b45c8e95ac2fd0055a

**Pull request closed without merging**
